name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_typecheck:
    name: Lint & Typecheck
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Lint code
        run: npm run lint
      - name: TypeScript Check
        run: npx tsc --noEmit
