name: Preview Builds

on:
  pull_request:
    branches:
      - main

jobs:
  build_android:
    name: Build Android (Preview)
    type: build
    params:
      platform: android
      profile: preview
