name: Publish EAS Update

on:
  push:
    branches:
      - main

jobs:
  publish_update:
    name: Publish Android Update
    type: update
    params:
      branch: production
      platform: android
      message: 'Publish update from ${{ github.sha }}'
